durations:
  minutes_default: 60
  presets: [5, 20, 60]

withers:
  enable: true
  spawn_after_minutes: 60
  taunts:
    enable: true
    every_ticks: 1200
    lines:
      - "[WITHER] Ich bin die Leere zwischen euren Sternen…"
      - "[WITHER] Eure Hoffnung zerbricht wie Glas."
      - "[WITHER] Atmet Staub, Sterbliche."

wipes:
  entity_soft_every_ticks: 3600
  radius: 300
  hardwipe:
    radius: 1500
    armorstand_radius: 5000

rewards:
  mode: "all"
  on_boss_kill:
    commands:
      - "eco give %player% 5000"
      - "broadcast &a%player% hat LuckySky gewonnen!"
  on_fail:
    commands:
      - "tellraw %player% {\"text\":\"Schade! Nächstes Mal!\",\"color\":\"gray\"}"

lives:
  one_life: false
